
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 10 18:50:39 CET 2019
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FUNCTION = 18;
  public static final int RIGHT_BRACKET = 34;
  public static final int ASTERISK = 41;
  public static final int SUBPROGRAM = 25;
  public static final int COMMENT = 2;
  public static final int CONSTANTS = 9;
  public static final int INTEGER = 13;
  public static final int VECTOR_ACCESS = 45;
  public static final int LESS = 42;
  public static final int FOR = 20;
  public static final int WRITE = 15;
  public static final int SEMICOLON = 36;
  public static final int NOT = 19;
  public static final int AND = 30;
  public static final int RANGE = 38;
  public static final int IN = 11;
  public static final int COMMA = 35;
  public static final int BEGIN = 8;
  public static final int RIGHT_PARENTHESIS = 32;
  public static final int PLUS = 40;
  public static final int ASSIGN = 44;
  public static final int IF = 23;
  public static final int DOT = 39;
  public static final int ID = 5;
  public static final int OF = 10;
  public static final int EOF = 0;
  public static final int BOOLEAN = 6;
  public static final int RETURN = 12;
  public static final int EQUAL = 43;
  public static final int TRUE = 7;
  public static final int error = 1;
  public static final int PROGRAM = 22;
  public static final int NUMBER = 3;
  public static final int VECTOR = 29;
  public static final int COLON = 37;
  public static final int ELSE = 24;
  public static final int VARIABLES = 28;
  public static final int THEN = 14;
  public static final int END = 17;
  public static final int STRING = 4;
  public static final int TYPES = 26;
  public static final int FALSE = 16;
  public static final int LEFT_BRACKET = 33;
  public static final int VAR = 27;
  public static final int PROCEDURE = 21;
  public static final int LEFT_PARENTHESIS = 31;
}

