/* The following code was generated by JFlex 1.4.1 on 10/02/19 20:50 */

package compiler.lexical;

import compiler.syntax.sym;
import compiler.lexical.Token;
import es.uned.lsi.compiler.lexical.ScannerIF;
import es.uned.lsi.compiler.lexical.LexicalError;
import es.uned.lsi.compiler.lexical.LexicalErrorManager;

// incluir aqui, si es necesario otras importaciones


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 10/02/19 20:50 from the specification file
 * <tt>C:/Users/sergi/eclipse-workspace/ArquitecturaPLI-2018-2019/doc/specs/scanner.flex</tt>
 */
public class Scanner implements java_cup.runtime.Scanner, ScannerIF {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  3,  0,  1,  2,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  0,  7,  4,  0,  0,  0,  0, 30, 31, 39, 38, 34,  0, 37,  0, 
     5,  6,  6,  6,  6,  6,  6,  6,  6,  6, 36, 35, 40, 41,  0,  0, 
     0,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8, 
     8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8, 32,  0, 33,  0,  9, 
     0, 14, 10, 16, 23, 13, 25, 28,  8, 17,  8,  8, 12, 20, 15, 11, 
    27,  8, 18, 22, 19, 26, 24,  8,  8, 29, 21,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\2\3\1\1\1\4\1\1"+
    "\12\4\1\5\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\3\0\1\22"+
    "\1\4\1\23\1\4\1\24\3\4\1\25\1\4\1\26"+
    "\7\4\1\27\1\30\1\31\13\4\1\32\1\4\1\33"+
    "\13\4\1\34\6\4\1\35\11\4\1\36\4\4\1\37"+
    "\5\4\1\40\3\4\1\41\2\4\1\42\14\4\1\43"+
    "\2\4\1\44\1\45\1\46\1\4\1\47\1\4\1\50"+
    "\2\4\1\51\2\4\1\52\1\4\1\53\4\4\1\54"+
    "\1\4\1\55";

  private static int [] zzUnpackAction() {
    int [] result = new int[154];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\52\0\124\0\52\0\176\0\250\0\322"+
    "\0\374\0\u0126\0\u0150\0\u017a\0\u01a4\0\u01ce\0\u01f8\0\u0222"+
    "\0\u024c\0\u0276\0\u02a0\0\322\0\52\0\52\0\u02ca\0\52"+
    "\0\52\0\52\0\52\0\u02f4\0\52\0\52\0\52\0\u031e"+
    "\0\124\0\u0348\0\250\0\250\0\u0372\0\u039c\0\u03c6\0\322"+
    "\0\u03f0\0\u041a\0\u0444\0\u046e\0\u0498\0\u04c2\0\u04ec\0\u0516"+
    "\0\u0540\0\u056a\0\u0594\0\u05be\0\u05e8\0\52\0\52\0\52"+
    "\0\u0612\0\u063c\0\u0666\0\u0690\0\u06ba\0\u06e4\0\u070e\0\u0738"+
    "\0\u0762\0\u078c\0\u07b6\0\u07e0\0\u080a\0\322\0\u0834\0\u085e"+
    "\0\u0888\0\u08b2\0\u08dc\0\u0906\0\u0930\0\u095a\0\u0984\0\u09ae"+
    "\0\u09d8\0\322\0\u0a02\0\u0a2c\0\u0a56\0\u0a80\0\u0aaa\0\u0ad4"+
    "\0\322\0\u0afe\0\u0b28\0\u0b52\0\u0b7c\0\u0ba6\0\u0bd0\0\u0bfa"+
    "\0\u0c24\0\u0c4e\0\322\0\u0c78\0\u0ca2\0\u0ccc\0\u0cf6\0\322"+
    "\0\u0d20\0\u0d4a\0\u0d74\0\u0d9e\0\u0dc8\0\322\0\u0df2\0\u0e1c"+
    "\0\u0e46\0\322\0\u0e70\0\u0e9a\0\322\0\u0ec4\0\u0eee\0\u0f18"+
    "\0\u0f42\0\u0f6c\0\u0f96\0\u0fc0\0\u0fea\0\u1014\0\u103e\0\u1068"+
    "\0\u1092\0\322\0\u10bc\0\u10e6\0\322\0\322\0\322\0\u1110"+
    "\0\322\0\u113a\0\322\0\u1164\0\u118e\0\322\0\u11b8\0\u11e2"+
    "\0\322\0\u120c\0\322\0\u1236\0\u1260\0\u128a\0\u12b4\0\322"+
    "\0\u12de\0\322";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[154];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\3\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\2\10\1\13\1\10\1\14\1\15\2\10\1\16"+
    "\2\10\1\17\1\20\1\21\1\22\1\10\1\23\1\10"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\52\0\2\41\1\42"+
    "\1\0\46\41\5\0\2\6\43\0\3\43\1\0\3\43"+
    "\1\44\42\43\5\0\2\10\1\0\1\10\1\0\24\10"+
    "\24\0\1\10\1\0\24\10\21\0\2\10\1\0\1\10"+
    "\1\0\1\10\1\45\22\10\21\0\2\10\1\0\1\10"+
    "\1\0\5\10\1\46\6\10\1\47\7\10\21\0\2\10"+
    "\1\0\1\10\1\0\1\10\1\50\22\10\21\0\2\10"+
    "\1\0\1\10\1\0\1\10\1\51\5\10\1\52\14\10"+
    "\21\0\2\10\1\0\1\10\1\0\7\10\1\53\14\10"+
    "\21\0\2\10\1\0\1\10\1\0\7\10\1\54\10\10"+
    "\1\55\3\10\21\0\2\10\1\0\1\10\1\0\3\10"+
    "\1\56\20\10\21\0\2\10\1\0\1\10\1\0\3\10"+
    "\1\57\1\60\17\10\21\0\2\10\1\0\1\10\1\0"+
    "\4\10\1\61\2\10\1\62\10\10\1\63\3\10\21\0"+
    "\2\10\1\0\1\10\1\0\4\10\1\64\3\10\1\65"+
    "\13\10\55\0\1\66\55\0\1\67\55\0\1\70\2\41"+
    "\1\42\1\3\46\41\5\0\2\10\1\0\1\10\1\0"+
    "\1\10\1\71\22\10\21\0\2\10\1\0\1\10\1\0"+
    "\11\10\1\72\12\10\21\0\2\10\1\0\1\10\1\0"+
    "\6\10\1\73\15\10\21\0\2\10\1\0\1\10\1\0"+
    "\5\10\1\74\4\10\1\75\11\10\21\0\2\10\1\0"+
    "\1\10\1\0\3\10\1\76\20\10\21\0\2\10\1\0"+
    "\1\10\1\0\21\10\1\77\2\10\21\0\2\10\1\0"+
    "\1\10\1\0\5\10\1\100\16\10\21\0\2\10\1\0"+
    "\1\10\1\0\1\101\23\10\21\0\2\10\1\0\1\10"+
    "\1\0\16\10\1\102\5\10\21\0\2\10\1\0\1\10"+
    "\1\0\6\10\1\103\15\10\21\0\2\10\1\0\1\10"+
    "\1\0\10\10\1\104\13\10\21\0\2\10\1\0\1\10"+
    "\1\0\2\10\1\105\21\10\21\0\2\10\1\0\1\10"+
    "\1\0\5\10\1\106\16\10\21\0\2\10\1\0\1\10"+
    "\1\0\5\10\1\107\16\10\21\0\2\10\1\0\1\10"+
    "\1\0\10\10\1\110\13\10\21\0\2\10\1\0\1\10"+
    "\1\0\1\10\1\111\22\10\21\0\2\10\1\0\1\10"+
    "\1\0\2\10\1\112\21\10\21\0\2\10\1\0\1\10"+
    "\1\0\1\10\1\113\1\10\1\114\20\10\21\0\2\10"+
    "\1\0\1\10\1\0\10\10\1\115\13\10\21\0\2\10"+
    "\1\0\1\10\1\0\14\10\1\116\7\10\21\0\2\10"+
    "\1\0\1\10\1\0\7\10\1\117\14\10\21\0\2\10"+
    "\1\0\1\10\1\0\10\10\1\120\13\10\21\0\2\10"+
    "\1\0\1\10\1\0\1\10\1\121\22\10\21\0\2\10"+
    "\1\0\1\10\1\0\1\10\1\122\22\10\21\0\2\10"+
    "\1\0\1\10\1\0\21\10\1\123\2\10\21\0\2\10"+
    "\1\0\1\10\1\0\1\10\1\124\22\10\21\0\2\10"+
    "\1\0\1\10\1\0\11\10\1\125\12\10\21\0\2\10"+
    "\1\0\1\10\1\0\7\10\1\126\14\10\21\0\2\10"+
    "\1\0\1\10\1\0\14\10\1\127\7\10\21\0\2\10"+
    "\1\0\1\10\1\0\6\10\1\130\15\10\21\0\2\10"+
    "\1\0\1\10\1\0\4\10\1\131\17\10\21\0\2\10"+
    "\1\0\1\10\1\0\6\10\1\132\13\10\1\133\1\10"+
    "\21\0\2\10\1\0\1\10\1\0\3\10\1\134\20\10"+
    "\21\0\2\10\1\0\1\10\1\0\5\10\1\135\16\10"+
    "\21\0\2\10\1\0\1\10\1\0\10\10\1\136\13\10"+
    "\21\0\2\10\1\0\1\10\1\0\7\10\1\137\14\10"+
    "\21\0\2\10\1\0\1\10\1\0\11\10\1\140\12\10"+
    "\21\0\2\10\1\0\1\10\1\0\3\10\1\141\20\10"+
    "\21\0\2\10\1\0\1\10\1\0\11\10\1\142\12\10"+
    "\21\0\2\10\1\0\1\10\1\0\14\10\1\143\7\10"+
    "\21\0\2\10\1\0\1\10\1\0\10\10\1\144\13\10"+
    "\21\0\2\10\1\0\1\10\1\0\2\10\1\145\21\10"+
    "\21\0\2\10\1\0\1\10\1\0\1\10\1\146\22\10"+
    "\21\0\2\10\1\0\1\10\1\0\4\10\1\147\17\10"+
    "\21\0\2\10\1\0\1\10\1\0\1\10\1\150\22\10"+
    "\21\0\2\10\1\0\1\10\1\0\7\10\1\151\14\10"+
    "\21\0\2\10\1\0\1\10\1\0\3\10\1\152\20\10"+
    "\21\0\2\10\1\0\1\10\1\0\10\10\1\153\13\10"+
    "\21\0\2\10\1\0\1\10\1\0\4\10\1\154\17\10"+
    "\21\0\2\10\1\0\1\10\1\0\6\10\1\155\15\10"+
    "\21\0\2\10\1\0\1\10\1\0\1\10\1\156\22\10"+
    "\21\0\2\10\1\0\1\10\1\0\1\157\23\10\21\0"+
    "\2\10\1\0\1\10\1\0\4\10\1\160\17\10\21\0"+
    "\2\10\1\0\1\10\1\0\5\10\1\161\16\10\21\0"+
    "\2\10\1\0\1\10\1\0\1\10\1\162\22\10\21\0"+
    "\2\10\1\0\1\10\1\0\1\10\1\163\22\10\21\0"+
    "\2\10\1\0\1\10\1\0\16\10\1\164\5\10\21\0"+
    "\2\10\1\0\1\10\1\0\10\10\1\165\13\10\21\0"+
    "\2\10\1\0\1\10\1\0\1\166\23\10\21\0\2\10"+
    "\1\0\1\10\1\0\1\10\1\167\22\10\21\0\2\10"+
    "\1\0\1\10\1\0\15\10\1\170\6\10\21\0\2\10"+
    "\1\0\1\10\1\0\4\10\1\171\17\10\21\0\2\10"+
    "\1\0\1\10\1\0\5\10\1\172\16\10\21\0\2\10"+
    "\1\0\1\10\1\0\3\10\1\173\20\10\21\0\2\10"+
    "\1\0\1\10\1\0\7\10\1\174\14\10\21\0\2\10"+
    "\1\0\1\10\1\0\5\10\1\175\16\10\21\0\2\10"+
    "\1\0\1\10\1\0\13\10\1\176\10\10\21\0\2\10"+
    "\1\0\1\10\1\0\22\10\1\177\1\10\21\0\2\10"+
    "\1\0\1\10\1\0\3\10\1\200\20\10\21\0\2\10"+
    "\1\0\1\10\1\0\2\10\1\201\21\10\21\0\2\10"+
    "\1\0\1\10\1\0\5\10\1\202\16\10\21\0\2\10"+
    "\1\0\1\10\1\0\7\10\1\203\14\10\21\0\2\10"+
    "\1\0\1\10\1\0\12\10\1\204\11\10\21\0\2\10"+
    "\1\0\1\10\1\0\1\10\1\205\22\10\21\0\2\10"+
    "\1\0\1\10\1\0\14\10\1\206\7\10\21\0\2\10"+
    "\1\0\1\10\1\0\10\10\1\207\13\10\21\0\2\10"+
    "\1\0\1\10\1\0\11\10\1\210\12\10\21\0\2\10"+
    "\1\0\1\10\1\0\1\10\1\211\22\10\21\0\2\10"+
    "\1\0\1\10\1\0\10\10\1\212\13\10\21\0\2\10"+
    "\1\0\1\10\1\0\10\10\1\213\13\10\21\0\2\10"+
    "\1\0\1\10\1\0\3\10\1\214\20\10\21\0\2\10"+
    "\1\0\1\10\1\0\12\10\1\215\11\10\21\0\2\10"+
    "\1\0\1\10\1\0\4\10\1\216\17\10\21\0\2\10"+
    "\1\0\1\10\1\0\3\10\1\217\20\10\21\0\2\10"+
    "\1\0\1\10\1\0\4\10\1\220\17\10\21\0\2\10"+
    "\1\0\1\10\1\0\14\10\1\221\7\10\21\0\2\10"+
    "\1\0\1\10\1\0\7\10\1\222\14\10\21\0\2\10"+
    "\1\0\1\10\1\0\14\10\1\223\7\10\21\0\2\10"+
    "\1\0\1\10\1\0\12\10\1\224\11\10\21\0\2\10"+
    "\1\0\1\10\1\0\3\10\1\225\20\10\21\0\2\10"+
    "\1\0\1\10\1\0\4\10\1\226\17\10\21\0\2\10"+
    "\1\0\1\10\1\0\5\10\1\227\16\10\21\0\2\10"+
    "\1\0\1\10\1\0\14\10\1\230\7\10\21\0\2\10"+
    "\1\0\1\10\1\0\11\10\1\231\12\10\21\0\2\10"+
    "\1\0\1\10\1\0\1\10\1\232\22\10\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4872];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\1\11\17\1\2\11\1\1\4\11"+
    "\1\1\3\11\1\1\3\0\22\1\3\11\142\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[154];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	LexicalErrorManager lexicalErrorManager = new LexicalErrorManager ();
	private int commentCount = 0;
	
	Token createToken(int id) {
		Token token = new Token(id);
		token.setLine(yyline + 1);
		token.setColumn(yycolumn + 1);
		token.setLexema(yytext());
		return token;
	}
	
	void createError() {
		LexicalError error = new LexicalError ();
		error.setLine (yyline + 1);
		error.setColumn (yycolumn + 1);
		error.setLexema (yytext ());
		lexicalErrorManager.lexicalError (error);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) throws LexicalError {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new LexicalError(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  throws LexicalError {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException, LexicalError {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 28: 
          { return createToken(sym.ELSE);
          }
        case 46: break;
        case 7: 
          { return createToken(sym.RIGHT_PARENTHESIS);
          }
        case 47: break;
        case 27: 
          { return createToken(sym.END);
          }
        case 48: break;
        case 37: 
          { return createToken(sym.THEN);
          }
        case 49: break;
        case 44: 
          { return createToken(sym.SUBPROGRAM);
          }
        case 50: break;
        case 22: 
          { return createToken(sym.OF);
          }
        case 51: break;
        case 15: 
          { return createToken(sym.ASTERISK);
          }
        case 52: break;
        case 20: 
          { return createToken(sym.NOT);
          }
        case 53: break;
        case 5: 
          { return createToken(sym.AND);
          }
        case 54: break;
        case 3: 
          { return createToken(sym.NUMBER);
          }
        case 55: break;
        case 1: 
          { createError();
          }
        case 56: break;
        case 10: 
          { return createToken(sym.COMMA);
          }
        case 57: break;
        case 30: 
          { return createToken(sym.TYPES);
          }
        case 58: break;
        case 8: 
          { return createToken(sym.LEFT_BRACKET);
          }
        case 59: break;
        case 18: 
          { return createToken(sym.STRING);
          }
        case 60: break;
        case 31: 
          { return createToken(sym.FALSE);
          }
        case 61: break;
        case 32: 
          { return createToken(sym.INTEGER);
          }
        case 62: break;
        case 38: 
          { return createToken(sym.WRITE);
          }
        case 63: break;
        case 36: 
          { return createToken(sym.BOOLEAN);
          }
        case 64: break;
        case 26: 
          { return createToken(sym.VAR);
          }
        case 65: break;
        case 23: 
          { return createToken(sym.VECTOR_ACCESS);
          }
        case 66: break;
        case 45: 
          { return createToken(sym.PROCEDURE);
          }
        case 67: break;
        case 29: 
          { return createToken(sym.FOR);
          }
        case 68: break;
        case 41: 
          { return createToken(sym.PROGRAM);
          }
        case 69: break;
        case 35: 
          { return createToken(sym.FUNCTION);
          }
        case 70: break;
        case 11: 
          { return createToken(sym.SEMICOLON);
          }
        case 71: break;
        case 39: 
          { return createToken(sym.BEGIN);
          }
        case 72: break;
        case 21: 
          { return createToken(sym.IF);
          }
        case 73: break;
        case 43: 
          { return createToken(sym.CONSTANTS);
          }
        case 74: break;
        case 9: 
          { return createToken(sym.RIGHT_BRACKET);
          }
        case 75: break;
        case 17: 
          { return createToken(sym.ASSIGN);
          }
        case 76: break;
        case 19: 
          { return createToken(sym.IN);
          }
        case 77: break;
        case 40: 
          { return createToken(sym.RETURN);
          }
        case 78: break;
        case 6: 
          { return createToken(sym.LEFT_PARENTHESIS);
          }
        case 79: break;
        case 42: 
          { return createToken(sym.VARIABLES);
          }
        case 80: break;
        case 12: 
          { return createToken(sym.COLON);
          }
        case 81: break;
        case 34: 
          { return createToken(sym.VECTOR);
          }
        case 82: break;
        case 13: 
          { return createToken(sym.DOT);
          }
        case 83: break;
        case 14: 
          { return createToken(sym.PLUS);
          }
        case 84: break;
        case 4: 
          { return createToken(sym.ID);
          }
        case 85: break;
        case 24: 
          { return createToken(sym.RANGE);
          }
        case 86: break;
        case 16: 
          { return createToken(sym.LESS);
          }
        case 87: break;
        case 33: 
          { return createToken(sym.TRUE);
          }
        case 88: break;
        case 2: 
          { 
          }
        case 89: break;
        case 25: 
          { return createToken(sym.EQUAL);
          }
        case 90: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
